# Service for OpenFOAM application
apiVersion: v1
kind: Service
metadata:
  name: svc-openfoam
  namespace: default
  annotations:
    haproxy.org/load-balance: "leastconn"  # Use least connections for load balancing
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4242
  selector:
    app: openfoam
---

# Ingress for OpenFOAM application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openfoam-ingress
  annotations:
    haproxy.org/rewrite-target: /$1
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /openfoam/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: svc-openfoam
                port:
                  number: 80
# ---
# # Service for Cookies application
# apiVersion: v1
# kind: Service
# metadata:
#   name: svc-cookies
#   namespace: default
#   annotations:
#     haproxy.org/load-balance: "leastconn"  # Use least connections for load balancing
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 4242
#   selector:
#     app: cookies
# ---
# # Ingress for Cookies application
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cookies-ingress
#   annotations:
#     haproxy.org/rewrite-target: /$1
# spec:
#   ingressClassName: haproxy
#   rules:
#     - http:
#         paths:
#           - path: /cookies/(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: svc-cookies
#                 port:
#                   number: 80
---
# ConfigMap for HAProxy Ingress Controller
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-ingress
  namespace: haproxy-controller
data:
  timeout-server: 48h
  timeout-connect: 48h
  timeout-queue: 48h
  timeout-http-request: 48h
  syslog-server: "address:stdout, format:raw, facility:daemon"
  log-format: '%ci:%cp [%t] %ft %b/%s %HM %HV %TR/%Tw/%Tc/%Tt %B %s'
  log-level: debug