apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  selector:
    matchLabels:
      app: model
  replicas: 8
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: benmkent/openfoam2dwmh:latest
        imagePullPolicy: "Always"
        env:
        - name: OMP_NUM_THREADS
          value: "1"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /outputdata
          name: outputhost-volume
      volumes:
      - name: outputhost-volume
        persistentVolumeClaim:
          claimName: outputhost-pvc