# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: outputhost-pv-dg
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/benkent/Documents/GitHub/umbridge-servers/doubleglazing/outputdata  # Change this to the absolute path on your host