apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment-cookies
spec:
  selector:
    matchLabels:
      app: model-cookies
  replicas: 8
  template:
    metadata:
      labels:
        app: model-cookies
    spec:
      containers:
      - name: model-cookies
        image: benmkent/cookiebenchmark:latest
        imagePullPolicy: "Always"
        env:
        - name: OMP_NUM_THREADS
          value: "1"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
