apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-darcy
spec:
  selector:
    matchLabels:
      app: darcy
  replicas: 6
  template:
    metadata:
      labels:
        app: darcy
    spec:
      containers:
      - name: darcy
        image: benmkent/darcy:latest
        imagePullPolicy: "Always"
        env:
        - name: OMP_NUM_THREADS
          value: "1"
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
