apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: default
  annotations:
    haproxy.org/load-balance: "leastconn"

spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4242
  selector:
    app: model
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-svc
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-ingress
  namespace: haproxy-controller
data:
  timeout-server: 1h
  timeout-connect: 1h
  timeout-queue: 1h
  timeout-http-request: 1h
  syslog-server: "address:stdout, format:raw, facility:daemon"
  #auth-type: basic-auth
  #auth-secret: haproxy-controller/haproxy-credentials
